import { Helmet } from "react-helmet-async";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const Privacy = () => {
  return (
    <>
      <Helmet>
        <title>Privacy Policy - Medical Terms Game</title>
        <meta name="description" content="Our privacy policy and data protection compliance information." />
      </Helmet>

      <div className="container mx-auto max-w-4xl py-12 px-4">
        <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>1. Introduction</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              This Privacy Policy explains how we collect, use, store, and protect your personal data in
              compliance with the General Data Protection Regulation (GDPR), the California Consumer 
              Privacy Act (CCPA), Israel's Protection of Privacy Law (including Amendment 13 effective 
              August 2025), and other applicable privacy laws.
            </p>
            <p>
              We are committed to protecting your privacy and ensuring you have a positive experience
              on our website. This policy applies to all users worldwide and provides comprehensive 
              information about your data rights under various privacy regulations.
            </p>
            <p>
              <strong>Data Controller:</strong> Nick, Med-Ivrit Project, located in Haifa, Israel, is 
              the data controller responsible for your personal data.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>2. Data We Collect</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h3 className="font-semibold mb-2">2.1 Account Information</h3>
              <p>We offer two authentication methods, and the data collected depends on which method you choose:</p>
              <p className="mt-2"><strong>Google OAuth Authentication:</strong></p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Email address</li>
                <li>Full name</li>
                <li>Google profile picture URL</li>
                <li>Google User ID (for authentication purposes)</li>
              </ul>
              <p className="mt-2"><strong>Email and Password Registration (via Supabase):</strong></p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Email address</li>
                <li>Encrypted password (we never store plain-text passwords)</li>
              </ul>
              <p className="mt-2"><strong>Common to Both Methods:</strong></p>
              <ul className="list-disc pl-6 space-y-1">
                <li>User ID (automatically generated by our system)</li>
                <li>Account creation date and time</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2">2.2 Learning Progress and Usage Data</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Words you've marked as mastered</li>
                <li>Your learning statistics and progress metrics</li>
                <li>Session timestamps and activity logs</li>
                <li>Language preferences (Hebrew, Russian, English)</li>
                <li>Feature usage patterns (which tools and features you use)</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2">2.3 Consent Records</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Your explicit consent preferences for data processing</li>
                <li>Consent timestamps (when consent was given or withdrawn)</li>
                <li>User agent information (browser and device type, optional, for consent verification)</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2">2.4 Technical and Security Data</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Browser type and version</li>
                <li>Device type and operating system</li>
                <li>IP address (for security, fraud prevention, and geographic compliance)</li>
                <li>Session data and authentication tokens (encrypted)</li>
                <li>Error logs and diagnostic information (for troubleshooting)</li>
              </ul>
            </div>
            <p className="mt-4 font-semibold">
              We do NOT collect: Payment information (service is free), sensitive health data, precise 
              geolocation, biometric data, or any special categories of personal data under GDPR.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>3. How We Use Your Data</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>We use your personal data only for the following legitimate purposes:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Service Provision:</strong> To provide, maintain, and improve our medical terminology learning platform</li>
              <li><strong>Authentication and Account Management:</strong> To verify your identity, secure your account, and manage access through Google OAuth or email/password authentication</li>
              <li><strong>Progress Tracking:</strong> To save, synchronize, and display your learning progress across devices</li>
              <li><strong>Personalization:</strong> To customize your learning experience based on your preferences and progress</li>
              <li><strong>Communication:</strong> To send you essential service updates, security alerts, and respond to your inquiries (marketing communications only with explicit consent)</li>
              <li><strong>Security and Fraud Prevention:</strong> To detect, prevent, and respond to security incidents, fraud, or abuse</li>
              <li><strong>Legal Compliance:</strong> To comply with legal obligations, respond to lawful requests, and protect our legal rights</li>
              <li><strong>Analytics and Improvement:</strong> To analyze usage patterns and improve service quality (using aggregated, anonymized data)</li>
            </ul>
            <p className="mt-4 font-semibold">
              We do NOT sell, rent, or share your personal data with third parties for their marketing 
              purposes. We do NOT use your data for automated decision-making or profiling that produces 
              legal or similarly significant effects.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>4. Legal Basis for Processing</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>Under GDPR and other privacy laws, we process your personal data based on the following legal grounds:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Consent (GDPR Art. 6(1)(a)):</strong> You have given explicit, informed consent for specific processing activities, such as creating an account and storing your learning data</li>
              <li><strong>Contract Performance (GDPR Art. 6(1)(b)):</strong> Processing is necessary to provide our service and fulfill our agreement with you</li>
              <li><strong>Legal Obligation (GDPR Art. 6(1)(c)):</strong> We must process data to comply with legal requirements, such as data retention obligations or responding to lawful requests</li>
              <li><strong>Legitimate Interests (GDPR Art. 6(1)(f)):</strong> Processing is necessary for our legitimate interests (e.g., security, fraud prevention, service improvement), provided your rights and interests do not override these interests</li>
            </ul>
            <p className="mt-4">
              You have the right to withdraw consent at any time, which will not affect the lawfulness of 
              processing based on consent before its withdrawal.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>5. Data Storage and Security</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h3 className="font-semibold mb-2">5.1 Where Your Data is Stored</h3>
              <p>
                Your personal data is stored using Supabase, a cloud database service, with data physically 
                located in the <strong>US East (United States)</strong> region. Our website frontend is 
                hosted on Netlify's global content delivery network (CDN).
              </p>
            </div>
            <div>
              <h3 className="font-semibold mb-2">5.2 Security Measures</h3>
              <p>
                We implement industry-standard technical and organizational measures to protect your data:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Encryption:</strong> Data is encrypted at rest (in our database) and in transit (TLS/SSL) using industry-standard protocols</li>
                <li><strong>Authentication:</strong> Secure authentication via Google OAuth 2.0 or Supabase email/password with token-based access</li>
                <li><strong>Access Controls:</strong> Strict access controls and authentication requirements for all systems</li>
                <li><strong>Row-Level Security (RLS):</strong> Database-level security policies ensure users can only access their own data</li>
                <li><strong>Regular Security Updates:</strong> We keep all software dependencies and security patches up to date</li>
                <li><strong>Monitoring:</strong> Continuous monitoring for suspicious activity and security threats</li>
                <li><strong>Secure Infrastructure:</strong> Our hosting providers (Supabase, Netlify) maintain SOC 2 Type II and ISO 27001 certifications</li>
                <li><strong>Limited Access:</strong> Only authorized personnel have access to systems containing personal data</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2">5.3 Data Breach Notification</h3>
              <p>
                In the unlikely event of a data breach that poses a risk to your rights and freedoms, we 
                will notify you and relevant supervisory authorities within 72 hours as required by GDPR 
                and other applicable laws.
              </p>
            </div>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>6. Your Privacy Rights</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>Depending on your location, you have the following rights under GDPR, CCPA, Israeli privacy law, and other regulations:</p>
            <div>
              <h3 className="font-semibold mb-2">6.1 Rights Under GDPR (EU/EEA users)</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Right to Access (Art. 15):</strong> Request a copy of all personal data we hold about you</li>
                <li><strong>Right to Rectification (Art. 16):</strong> Request correction of inaccurate or incomplete data</li>
                <li><strong>Right to Erasure / "Right to be Forgotten" (Art. 17):</strong> Request deletion of your personal data</li>
                <li><strong>Right to Restrict Processing (Art. 18):</strong> Request limitation of processing under certain circumstances</li>
                <li><strong>Right to Data Portability (Art. 20):</strong> Receive your data in a structured, machine-readable format (JSON/CSV) and transmit it to another controller</li>
                <li><strong>Right to Object (Art. 21):</strong> Object to processing based on legitimate interests or direct marketing</li>
                <li><strong>Right to Withdraw Consent (Art. 7(3)):</strong> Withdraw consent at any time for consent-based processing</li>
                <li><strong>Right to Lodge a Complaint:</strong> File a complaint with your national data protection authority</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2">6.2 Rights Under CCPA (California residents)</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Right to Know:</strong> Request disclosure of personal information we collect, use, and share</li>
                <li><strong>Right to Delete:</strong> Request deletion of personal information we collected from you</li>
                <li><strong>Right to Opt-Out:</strong> Opt-out of the sale of personal information (Note: We do NOT sell personal data)</li>
                <li><strong>Right to Non-Discrimination:</strong> You will not receive discriminatory treatment for exercising your privacy rights</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2">6.3 Rights Under Israeli Law (Amendment 13)</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Right to Access:</strong> Request information about what data we hold and how it's used</li>
                <li><strong>Right to Correction:</strong> Request correction of inaccurate data</li>
                <li><strong>Right to Deletion:</strong> Request deletion of your personal data (subject to legal retention requirements)</li>
                <li><strong>Right to Object:</strong> Object to certain processing activities</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2">6.4 How to Exercise Your Rights</h3>
              <p>
                You can exercise most rights directly from your <a href="/profile" className="text-primary hover:underline">Profile Settings</a> page, including:
              </p>
              <ul className="list-disc pl-6 space-y-1 mt-2">
                <li>Viewing your account information</li>
                <li>Updating your profile</li>
                <li>Exporting your data</li>
                <li>Requesting account deletion</li>
              </ul>
              <p className="mt-3">
                For other requests or questions about your privacy rights, please contact us through the 
                <a href="/ContactUs" className="text-primary hover:underline ml-1">Contact Us</a> page or email 
                contact.medivrit@gmail.com. We will respond to all requests within 30 days (or one month for 
                GDPR requests) as required by law.
              </p>
              <p className="mt-3 font-semibold">
                For EU residents: You have the right to lodge a complaint with your local data protection 
                supervisory authority if you believe we have violated your data protection rights.
              </p>
            </div>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>7. Account Deletion Process</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              You have the right to request deletion of your account and all associated personal data at 
              any time. When you submit a deletion request through your profile settings:
            </p>
            <ol className="list-decimal pl-6 space-y-2">
              <li>Your deletion request is processed through our Netlify Edge Function</li>
              <li>A notification is automatically sent to our team via Telegram, including your username and user ID</li>
              <li>We verify the authenticity of the request</li>
              <li>Your personal data is permanently deleted from our Supabase database within 30 days</li>
              <li>You will receive confirmation once deletion is complete</li>
            </ol>
            <p className="mt-4">
              <strong>What gets deleted:</strong> Your account information (email, name if provided, profile 
              picture if using Google OAuth), learning progress, mastered words, and all associated 
              user-generated data.
            </p>
            <p>
              <strong>Exceptions:</strong> We may retain certain data if required by law (e.g., for tax, 
              legal, or accounting purposes) or to resolve disputes and enforce our agreements. Such 
              retained data will be securely stored and access will be strictly limited.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>8. Data Retention</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              We retain your personal data only as long as necessary for the purposes outlined in this
              policy or as required by applicable laws:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Active Accounts:</strong> Data is retained as long as your account remains active</li>
              <li><strong>Inactive Accounts:</strong> If you don't use your account for 3 years, we may contact you to confirm whether you want to keep it active</li>
              <li><strong>Deleted Accounts:</strong> Upon deletion request, data is removed within 30 days</li>
              <li><strong>Legal Retention:</strong> Some data may be retained longer if required by law (e.g., financial records for 7 years)</li>
              <li><strong>Aggregated Data:</strong> We may retain anonymized, aggregated data indefinitely for statistical and analytical purposes</li>
            </ul>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>9. Third-Party Services and Data Sharing</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              We use the following third-party services to provide our platform. These providers have 
              access to certain personal data only to perform tasks on our behalf and are obligated not 
              to use it for other purposes:
            </p>
            <ul className="list-disc pl-6 space-y-3">
              <li>
                <strong>Google OAuth (Google LLC):</strong> For user authentication and account creation 
                (optional login method). Subject to <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Google's Privacy Policy</a>.
                We only access basic profile information (name, email, profile picture) with your explicit consent.
              </li>
              <li>
                <strong>Supabase (Supabase Inc.):</strong> For database hosting, data storage, and 
                authentication management (both Google OAuth and email/password methods). Data is stored in 
                US East region. Subject to <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline ml-1">Supabase's Privacy Policy</a>.
                Supabase is GDPR-compliant and SOC 2 Type II certified.
              </li>
              <li>
                <strong>Netlify (Netlify Inc.):</strong> For website hosting, content delivery (CDN), 
                and serverless edge functions. Subject to <a href="https://www.netlify.com/privacy" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline ml-1">Netlify's Privacy Policy</a>.
                Netlify is GDPR-compliant and SOC 2 Type II certified.
              </li>
              <li>
                <strong>Telegram (Telegram Messenger LLP):</strong> Used internally by our team to 
                receive notifications about account deletion requests. Only your username and user ID 
                are transmitted via secure edge functions. Telegram does not have access to your full 
                account data.
              </li>
            </ul>
            <p className="mt-4 font-semibold">
              We do NOT sell, rent, trade, or otherwise share your personal data with third parties for 
              their own marketing purposes. We do NOT use tracking pixels, advertising networks, or data 
              brokers.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>10. International Data Transfers</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              Your personal data is stored on Supabase servers located in the <strong>United States (US East region)</strong>. 
              If you are located in the European Economic Area (EEA), United Kingdom, Switzerland, or other 
              jurisdictions with data protection laws, this means your data is transferred outside your 
              jurisdiction.
            </p>
            <p>
              <strong>Safeguards for International Transfers:</strong>
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Our service providers (Supabase, Netlify) comply with GDPR requirements for international data transfers</li>
              <li>They use Standard Contractual Clauses (SCCs) approved by the European Commission</li>
              <li>They maintain robust security measures equivalent to GDPR standards</li>
              <li>Data is encrypted in transit and at rest</li>
            </ul>
            <p className="mt-4">
              For EEA users: By using our service, you acknowledge and consent to the transfer of your 
              data to the United States. You have the right to obtain information about the safeguards 
              we use for these transfers by contacting us.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>11. Cookies and Tracking Technologies</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              We use minimal cookies and similar tracking technologies necessary for the operation of our 
              service:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Essential Cookies:</strong> Required for authentication, session management, and security (e.g., login tokens, session IDs)</li>
              <li><strong>Authentication Tokens:</strong> Securely stored tokens from Google OAuth or Supabase for maintaining your logged-in session</li>
              <li><strong>Preference Cookies:</strong> Store your language preferences and UI settings</li>
            </ul>
            <p className="mt-4">
              We do NOT use:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Advertising or marketing cookies</li>
              <li>Third-party tracking cookies</li>
              <li>Analytics cookies (unless anonymized and with your consent)</li>
              <li>Social media tracking pixels</li>
            </ul>
            <p className="mt-4">
              You can control cookies through your browser settings, but disabling essential cookies may 
              affect the functionality of our service.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>12. Children's Privacy</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              Our service is intended for users aged 13 and older (or 16 and older for users in the 
              European Union). We do not knowingly collect personal data from children under these ages.
            </p>
            <p>
              If you are a parent or guardian and believe your child has provided us with personal data 
              without your consent, please contact us immediately at contact.medivrit@gmail.com. We will 
              take steps to delete such information from our systems within 30 days.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>13. Data Protection Officer (DPO)</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              Under Israeli Amendment 13, we are required to appoint a Data Protection Officer if we 
              maintain a database of more than 100,000 individuals. We are operated by individuals and 
              do not currently meet this threshold.
            </p>
            <p>
              For privacy-related inquiries, you can contact us through the 
              <a href="/ContactUs" className="text-primary hover:underline ml-1">Contact Us</a> page or 
              email contact.medivrit@gmail.com.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>14. California "Shine the Light" Law</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              California Civil Code Section 1798.83 permits California residents to request information 
              about the disclosure of personal information to third parties for direct marketing purposes.
            </p>
            <p>
              <strong>We do NOT share personal information with third parties for their direct marketing 
              purposes.</strong> Therefore, no such disclosures have been made.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>15. Updates to This Policy</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              We may update this Privacy Policy from time to time to reflect changes in our practices, 
              technology, legal requirements, or other factors. When we make material changes, we will:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Update the "Last Updated" date at the bottom of this policy</li>
              <li>Provide prominent notice on our website</li>
              <li>Send you an email notification (if you have an account)</li>
              <li>For material changes affecting your rights, seek your consent where required by law</li>
            </ul>
            <p className="mt-4">
              We encourage you to review this Privacy Policy periodically to stay informed about how we 
              protect your data. Your continued use of the service after changes become effective 
              constitutes acceptance of the updated policy.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>16. Contact Us</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p>
              If you have questions, concerns, or requests regarding this Privacy Policy or our data 
              practices, please contact us:
            </p>
            <ul className="list-none space-y-2 mt-3">
              <li><strong>Via Contact Form:</strong> <a href="/ContactUs" className="text-primary hover:underline">Contact Us page</a></li>
              <li><strong>Email:</strong> contact.medivrit@gmail.com</li>
              <li><strong>Postal Address:</strong> Nick, Med-Ivrit Project, Haifa, Israel</li>
            </ul>
            <p className="mt-4">
              <strong>For GDPR-related inquiries:</strong> If you are in the EU/EEA and wish to exercise 
              your rights or file a complaint, you may also contact your local data protection supervisory 
              authority.
            </p>
            <p className="mt-3">
              <strong>Response Time:</strong> We will respond to all legitimate requests within 30 days 
              (or one month for GDPR requests). In complex cases, we may extend this period by an 
              additional two months and will notify you of the extension.
            </p>
            <p className="text-sm text-muted-foreground mt-6">
              Last updated: {new Date().toLocaleDateString()}
            </p>
            <p className="text-sm text-muted-foreground">
              Effective date: {new Date().toLocaleDateString()}
            </p>
          </CardContent>
        </Card>
      </div>
    </>
  );
};

export default Privacy;