// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';

// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;

// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;


// export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY
//   , {
//     auth: {
//       storage: localStorage,
//       persistSession: true,
//       autoRefreshToken: true,
//     }
//   }
// );

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: async () => {
      const session = supabase.auth.getSession();
      const accessToken = session?.data?.session?.access_token;
      return accessToken
        ? { Authorization: `Bearer ${accessToken}` }
        : {};
    },
  },
});